import Head from 'next/head'
import { useSelector, useDispatch } from 'react-redux'
import {increment, decrement} from "../slices/counterSlice"

export default function Home() {
  const count = useSelector(state=>state.counter)
  const dispatch = useDispatch()
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{"width":"100%", "height":"100vh", "display":"flex","alignItems":"center", "justifyContent":"center","fontSize":"4rem"}}>
      <div style={{"display":"flex", "gap":"1rem"}}>
        <button
        style={{"fontSize":"4rem", "cursor":"pointer"}}
          aria-label="Increment value"
          onClick={() => dispatch(increment())}
        >
          Increment
        </button>
        <span>{count.value}</span>
        <button
        style={{"fontSize":"4rem", "cursor":"pointer"}}
          aria-label="Decrement value"
          onClick={() => dispatch(decrement())}
        >
          Decrement
        </button>
      </div>
    </div>
    </div>
  )
}
